name: Ubuntu 16.04 make

on:
  push:

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodules update --init --recursive
    - name: dependencies
      run: sudo apt update &&
           sudo apt install --assume-yes libcurl4-openssl-dev
    - name: make
      run: make
